import { NameDisplay } from './components/ChatNameContainer/types'

export const ChatNameHolder: NameDisplay[] = [
  { userId: 1, status: 'active', nickname: 'Alice' },
  { userId: 2, status: 'inactive', nickname: 'Bob' },
  { userId: 3, status: 'active', nickname: 'Charlie' },
  { userId: 4, status: 'inactive', nickname: 'Dave' },
  { userId: 5, status: 'active', nickname: 'Eve' },
  { userId: 6, status: 'inactive', nickname: 'Frank' },
  { userId: 7, status: 'active', nickname: 'Grace' },
  { userId: 8, status: 'inactive', nickname: 'Henry' },
  { userId: 9, status: 'active', nickname: 'Isabel' },
  { userId: 10, status: 'inactive', nickname: 'Jack' },
  { userId: 11, status: 'active', nickname: 'Kelly' },
  { userId: 12, status: 'inactive', nickname: 'Luke' },
  { userId: 13, status: 'active', nickname: 'Molly' },
  { userId: 14, status: 'inactive', nickname: 'Nate' },
  { userId: 15, status: 'active', nickname: 'Olivia' },
  { userId: 16, status: 'active', nickname: 'Molly' },
  { userId: 17, status: 'inactive', nickname: 'Nate' },
  { userId: 18, status: 'active', nickname: 'Olivia' },
  { userId: 9, status: 'active', nickname: 'Isabel' },
  { userId: 10, status: 'inactive', nickname: 'Jack' },
  { userId: 11, status: 'active', nickname: 'Kelly' },
  { userId: 12, status: 'inactive', nickname: 'Luke' },
  { userId: 13, status: 'active', nickname: 'Molly' },
  { userId: 14, status: 'inactive', nickname: 'Nate' },
  { userId: 15, status: 'active', nickname: 'Olivia' },
  { userId: 16, status: 'active', nickname: 'Molly' },
  { userId: 17, status: 'inactive', nickname: 'Nate' },
  { userId: 18, status: 'active', nickname: 'Olivia' },
]
